os: linux
language: android
licenses:
- android-sdk-preview-license-.+
- android-sdk-license-.+
- google-gdk-license-.+
android:
  components:
  - tools
  - platform-tools
  - build-tools-27.0.3
  - android-27
  - sys-img-armeabi-v7a-google_apis-25
  - extra-android-m2repository
  - extra-google-m2repository
  - extra-google-android-support
jdk: oraclejdk8
sudo: false
# 以上都是在安装AndroidSDK
env: APK_OUTPUT=build/app/outputs/apk/release/app-release.apk
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - libstdc++6
    - fonts-droid
#以上为Flutter环境搭建
before_script:
- git clone https://github.com/flutter/flutter.git -b stable
script:
- "./flutter/bin/flutter doctor"
- "./flutter/bin/flutter build apk --release"
deploy:
  provider: releases
  skip_cleanup: true
  file: $APK_OUTPUT
  on:
    tags: true

# 参考：https://juejin.im/post/5b20b5695188257d7d719bb6